// ini adalah model versi lama yang belum menggunakan json

class ToramMQ {
  int chapter;
  String chapterid;
  String chapteren;
  int episode;
  String episodeid;
  String episodeen;
  int exp;

  ToramMQ({
    required this.chapter,
    required this.chapterid,
    required this.chapteren,
    required this.episode,
    required this.episodeid,
    required this.episodeen,
    required this.exp,
  });
}

var toramMqList = [
  ToramMQ(
    chapter: 1,
    chapterid: "Awal Mula Kehancuran",
    chapteren: "The Beginning of Chaos",
    episode: 1,
    episodeid: "Pertemuan Baru",
    episodeen: "Firts Time Visit",
    exp: 30,
  ),
  ToramMQ(
    chapter: 1,
    chapterid: "Awal Mula Kehancuran",
    chapteren: "The Beginning of Chaos",
    episode: 2,
    episodeid: "Kakak Beradik Straye",
    episodeen: "Straye Brother and Sister",
    exp: 80,
  ),
  ToramMQ(
    chapter: 1,
    chapterid: "Awal Mula Kehancuran",
    chapteren: "The Beginning of Chaos",
    episode: 3,
    episodeid: "Golem Lepas Kendali",
    episodeen: "A Golem on a Rampage",
    exp: 730,
  ),
  ToramMQ(
    chapter: 1,
    chapterid: "Awal Mula Kehancuran",
    chapteren: "The Beginning of Chaos",
    episode: 4,
    episodeid: "Dewi Kearifan",
    episodeen: "The Goddes of Wisdom",
    exp: 2060,
  ),
  ToramMQ(
    chapter: 1,
    chapterid: "Awal Mula Kehancuran",
    chapteren: "The Beginning of Chaos",
    episode: 5,
    episodeid: "Gua Naga",
    episodeen: "The Dragon's Den",
    exp: 4700,
  ),
  ToramMQ(
    chapter: 1,
    chapterid: "Awal Mula Kehancuran",
    chapteren: "The Beginning of Chaos",
    episode: 6,
    episodeid: "Kuil Runtuh",
    episodeen: "The Ruined Temple",
    exp: 9330,
  ),
  ToramMQ(
    chapter: 1,
    chapterid: "Awal Mula Kehancuran",
    chapteren: "The Beginning of Chaos",
    episode: 7,
    episodeid: "Mestika Pertama",
    episodeen: "The First Magic Stone",
    exp: 16700,
  ),
  ToramMQ(
    chapter: 1,
    chapterid: "Awal Mula Kehancuran",
    chapteren: "The Beginning of Chaos",
    episode: 8,
    episodeid: "Dupa Pemurnian",
    episodeen: "Purification Incense",
    exp: 27900,
  ),
  ToramMQ(
    chapter: 1,
    chapterid: "Awal Mula Kehancuran",
    chapteren: "The Beginning of Chaos",
    episode: 9,
    episodeid: "Naga dan Kristal Hitam",
    episodeen: "The Dragon and Black Crystal",
    exp: 43000,
  ),
  ToramMQ(
    chapter: 2,
    chapterid: "Konflik Permata Suci",
    chapteren: "Look for Holy Gems!",
    episode: 10,
    episodeid: "Si Gadis Pedagang Tiba",
    episodeen: "The Merchant Girl",
    exp: 64000,
  ),
  ToramMQ(
    chapter: 2,
    chapterid: "Konflik Permata Suci",
    chapteren: "Look for Holy Gems!",
    episode: 11,
    episodeid: "Di Mana Permatanya?",
    episodeen: "Where Are the Gems?",
    exp: 92000,
  ),
  ToramMQ(
    chapter: 2,
    chapterid: "Konflik Permata Suci",
    chapteren: "Look for Holy Gems!",
    episode: 12,
    episodeid: "Ksatria Hitam Misterius",
    episodeen: "Who is the Black Knight?!",
    exp: 118200,
  ),
  ToramMQ(
    chapter: 2,
    chapterid: "Konflik Permata Suci",
    chapteren: "Look for Holy Gems!",
    episode: 13,
    episodeid: "Ujian Kastil Setan Bulan",
    episodeen: "Trials in the Palace",
    exp: 149000,
  ),
  ToramMQ(
    chapter: 2,
    chapterid: "Konflik Permata Suci",
    chapteren: "Look for Holy Gems!",
    episode: 14,
    episodeid: "Penyihir Rembulan",
    episodeen: "The Moon Wizard",
    exp: 172000,
  ),
  ToramMQ(
    chapter: 2,
    chapterid: "Konflik Permata Suci",
    chapteren: "Look for Holy Gems!",
    episode: 15,
    episodeid: "Pemuja dan Pendurja",
    episodeen: "The Follower and Hater",
    exp: 227000,
  ),
  ToramMQ(
    chapter: 2,
    chapterid: "Konflik Permata Suci",
    chapteren: "Look for Holy Gems!",
    episode: 16,
    episodeid: "Gua Penyihir",
    episodeen: "The Wizard's Cave",
    exp: 240000,
  ),
  ToramMQ(
    chapter: 2,
    chapterid: "Konflik Permata Suci",
    chapteren: "Look for Holy Gems!",
    episode: 17,
    episodeid: "Penyihir Bintang",
    episodeen: "The Star Wizard",
    exp: 255000,
  ),
  ToramMQ(
    chapter: 3,
    chapterid: "Pertikaian dengan Dewa Kuno",
    chapteren: "Battle with the Anient God",
    episode: 18,
    episodeid: "Musuh Terkuat. . . ?",
    episodeen: "The Invisible... Enemy??",
    exp: 270000,
  ),
  ToramMQ(
    chapter: 3,
    chapterid: "Pertikaian dengan Dewa Kuno",
    chapteren: "Battle with the Anient God",
    episode: 19,
    episodeid: "Ratu Kuno",
    episodeen: "The Ancient Empress",
    exp: 284000,
  ),
  ToramMQ(
    chapter: 3,
    chapterid: "Pertikaian dengan Dewa Kuno",
    chapteren: "Battle with the Anient God",
    episode: 20,
    episodeid: "Pelaku Terungkap",
    episodeen: "The Culprit",
    exp: 319000,
  ),
  ToramMQ(
    chapter: 3,
    chapterid: "Pertikaian dengan Dewa Kuno",
    chapteren: "Battle with the Anient God",
    episode: 21,
    episodeid: "Takdir Benteng Terungkap",
    episodeen: "Fate of the Fortress",
    exp: 335000,
  ),
  ToramMQ(
    chapter: 3,
    chapterid: "Pertikaian dengan Dewa Kuno",
    chapteren: "Battle with the Anient God",
    episode: 22,
    episodeid: "Kenangan Kota Hilang",
    episodeen: "Memory in the Lost Town",
    exp: 398000,
  ),
  ToramMQ(
    chapter: 3,
    chapterid: "Pertikaian dengan Dewa Kuno",
    chapteren: "Battle with the Anient God",
    episode: 23,
    episodeid: "Permata Sihir Terenggut",
    episodeen: "The Stolen Sorcery Gem",
    exp: 417000,
  ),
  ToramMQ(
    chapter: 3,
    chapterid: "Pertikaian dengan Dewa Kuno",
    chapteren: "Battle with the Anient God",
    episode: 24,
    episodeid: "Sahabat Kami adalah Naga",
    episodeen: "Living with a Dragon",
    exp: 462300,
  ),
  ToramMQ(
    chapter: 3,
    chapterid: "Pertikaian dengan Dewa Kuno",
    chapteren: "Battle with the Anient God",
    episode: 25,
    episodeid: "Monster dari Dunia Luar",
    episodeen: "Monsters from Outerworld",
    exp: 540000,
  ),
  ToramMQ(
    chapter: 4,
    chapterid: "Ancaman Bayangan Jahat",
    chapteren: "The Creeping Shadows",
    episode: 26,
    episodeid: "Para Penyihir Diel",
    episodeen: "The Mage Diels",
    exp: 562000,
  ),
  ToramMQ(
    chapter: 4,
    chapterid: "Ancaman Bayangan Jahat",
    chapteren: "The Creeping Shadows",
    episode: 27,
    episodeid: "Pencarian Jati Diri",
    episodeen: "Journey for Reconstruction",
    exp: 585000,
  ),
  ToramMQ(
    chapter: 4,
    chapterid: "Ancaman Bayangan Jahat",
    chapteren: "The Creeping Shadows",
    episode: 28,
    episodeid: "Permata Pusaka Akaku",
    episodeen: "The Sacred Gem in Akaku",
    exp: 710000,
  ),
  ToramMQ(
    chapter: 4,
    chapterid: "Ancaman Bayangan Jahat",
    chapteren: "The Creeping Shadows",
    episode: 29,
    episodeid: "Raja Darkan Agung",
    episodeen: "The King of Darkan",
    exp: 740000,
  ),
  ToramMQ(
    chapter: 4,
    chapterid: "Ancaman Bayangan Jahat",
    chapteren: "The Creeping Shadows",
    episode: 30,
    episodeid: "Geliat Kuasa Gelap",
    episodeen: "The Lurking Evil",
    exp: 803000,
  ),
  ToramMQ(
    chapter: 4,
    chapterid: "Ancaman Bayangan Jahat",
    chapteren: "The Creeping Shadows",
    episode: 31,
    episodeid: "Singkap Tipuannya!",
    episodeen: "Find the False Black Knight!",
    exp: 913000,
  ),
  ToramMQ(
    chapter: 4,
    chapterid: "Ancaman Bayangan Jahat",
    chapteren: "The Creeping Shadows",
    episode: 32,
    episodeid: "Gerakan Technista",
    episodeen: "Technista's Movement",
    exp: 1000000,
  ),
  ToramMQ(
    chapter: 4,
    chapterid: "Ancaman Bayangan Jahat",
    chapteren: "The Creeping Shadows",
    episode: 33,
    episodeid: "Bulu Sayap Maut Turun",
    episodeen: "The Falling Feather of Death",
    exp: 1100000,
  ),
  ToramMQ(
    chapter: 5,
    chapterid: "Badai di Kegelapan",
    chapteren: "The Strom in the Darkness",
    episode: 34,
    episodeid: "Dalam Kegelapan Tak Dikenal",
    episodeen: "In the Unknown Darkness",
    exp: 1150000,
  ),
  ToramMQ(
    chapter: 5,
    chapterid: "Badai di Kegelapan",
    chapteren: "The Strom in the Darkness",
    episode: 35,
    episodeid: "Azimat",
    episodeen: "The Charm",
    exp: 1310000,
  ),
  ToramMQ(
    chapter: 5,
    chapterid: "Badai di Kegelapan",
    chapteren: "The Strom in the Darkness",
    episode: 36,
    episodeid: "Cermin Kegelapan Kering",
    episodeen: "Parching Dark Mirror",
    exp: 1370000,
  ),
  ToramMQ(
    chapter: 5,
    chapterid: "Badai di Kegelapan",
    chapteren: "The Strom in the Darkness",
    episode: 37,
    episodeid: "Pertempuran Sengit di Taman",
    episodeen: "Fierce Battle in the Garden",
    exp: 1550000,
  ),
  ToramMQ(
    chapter: 5,
    chapterid: "Badai di Kegelapan",
    chapteren: "The Strom in the Darkness",
    episode: 38,
    episodeid: "Cahaya dalam Kegelapan",
    episodeen: "A Light in the Darkness",
    exp: 1750000,
  ),
  ToramMQ(
    chapter: 5,
    chapterid: "Badai di Kegelapan",
    chapteren: "The Strom in the Darkness",
    episode: 39,
    episodeid: "Dia yang Bersarang di Rumah",
    episodeen: "The Ones Nesting in the Manor",
    exp: 1970000,
  ),
  ToramMQ(
    chapter: 5,
    chapterid: "Badai di Kegelapan",
    chapteren: "The Strom in the Darkness",
    episode: 40,
    episodeid: "Istana Gelap",
    episodeen: "The Dark Castle",
    exp: 2210000,
  ),
  ToramMQ(
    chapter: 5,
    chapterid: "Badai di Kegelapan",
    chapteren: "The Strom in the Darkness",
    episode: 41,
    episodeid: "Menuju Dunia Penuh Kehidupan",
    episodeen: "To the World of the Living",
    exp: 2220000,
  ),
  ToramMQ(
    chapter: 6,
    chapterid: "Duo Technista",
    chapteren: "The Two Technista",
    episode: 42,
    episodeid: "Demi Machina",
    episodeen: "Demi Machina",
    exp: 2600000,
  ),
  ToramMQ(
    chapter: 6,
    chapterid: "Duo Technista",
    chapteren: "The Two Technista",
    episode: 43,
    episodeid: "Kota Faksi Pax",
    episodeen: "The Town of Pax Faction",
    exp: 2700000,
  ),
  ToramMQ(
    chapter: 6,
    chapterid: "Duo Technista",
    chapteren: "The Two Technista",
    episode: 44,
    episodeid: "Hati Mesin",
    episodeen: "Mechanical Heart",
    exp: 2800000,
  ),
  ToramMQ(
    chapter: 6,
    chapterid: "Duo Technista",
    chapteren: "The Two Technista",
    episode: 45,
    episodeid: "Ksatria Hitam Lyark",
    episodeen: "Black Knight of Lyark",
    exp: 2820000,
  ),
  ToramMQ(
    chapter: 6,
    chapterid: "Duo Technista",
    chapteren: "The Two Technista",
    episode: 46,
    episodeid: "Artefak Misterius",
    episodeen: "The Mysterious Artifact",
    exp: 3030000,
  ),
  ToramMQ(
    chapter: 6,
    chapterid: "Duo Technista",
    chapteren: "The Two Technista",
    episode: 47,
    episodeid: "Wujud Asli Artefak",
    episodeen: "Truth of the Artifact",
    exp: 3099000,
  ),
  ToramMQ(
    chapter: 6,
    chapterid: "Duo Technista",
    chapteren: "The Two Technista",
    episode: 48,
    episodeid: "Harga Pengkhianatan",
    episodeen: "The Price of Treachery",
    exp: 3320000,
  ),
  ToramMQ(
    chapter: 6,
    chapterid: "Duo Technista",
    chapteren: "The Two Technista",
    episode: 49,
    episodeid: "Pabrik Tercela",
    episodeen: "The Blasphemous Factory",
    exp: 3640000,
  ),
  ToramMQ(
    chapter: 6,
    chapterid: "Duo Technista",
    chapteren: "The Two Technista",
    episode: 50,
    episodeid: "Teka-Teki Ksatria Hitam",
    episodeen: "Mystery of the Black Knight",
    exp: 4020000,
  ),
  ToramMQ(
    chapter: 7,
    chapterid: "Pergolakan di Ultimea",
    chapteren: "Upheaval in Ultimea",
    episode: 51,
    episodeid: "Hutan Monster",
    episodeen: "Monster's Forest",
    exp: 4730000,
  ),
  ToramMQ(
    chapter: 7,
    chapterid: "Pergolakan di Ultimea",
    chapteren: "Upheaval in Ultimea",
    episode: 52,
    episodeid: "Kota Bawah Tanah",
    episodeen: "The Underground Town",
    exp: 4820000,
  ),
  ToramMQ(
    chapter: 7,
    chapterid: "Pergolakan di Ultimea",
    chapteren: "Upheaval in Ultimea",
    episode: 53,
    episodeid: "Elf di Wilayah Lyark",
    episodeen: "The Elves in Lyark",
    exp: 5070000,
  ),
  ToramMQ(
    chapter: 7,
    chapterid: "Pergolakan di Ultimea",
    chapteren: "Upheaval in Ultimea",
    episode: 54,
    episodeid: "Laboratorium Gila",
    episodeen: "The Mad Laboratory",
    exp: 5500000,
  ),
  ToramMQ(
    chapter: 7,
    chapterid: "Pergolakan di Ultimea",
    chapteren: "Upheaval in Ultimea",
    episode: 55,
    episodeid: "Tragedi di Penjara",
    episodeen: "Tragedy in the Jail",
    exp: 6000000,
  ),
  ToramMQ(
    chapter: 7,
    chapterid: "Pergolakan di Ultimea",
    chapteren: "Upheaval in Ultimea",
    episode: 56,
    episodeid: "Bencana di Alun-Alun Droma",
    episodeen: "Calamity in Droma Square",
    exp: 6400000,
  ),
  ToramMQ(
    chapter: 7,
    chapterid: "Pergolakan di Ultimea",
    chapteren: "Upheaval in Ultimea",
    episode: 57,
    episodeid: "Menuju Istana Ultimea",
    episodeen: "Head for Ultimea Palace",
    exp: 6900000,
  ),
  ToramMQ(
    chapter: 7,
    chapterid: "Pergolakan di Ultimea",
    chapteren: "Upheaval in Ultimea",
    episode: 58,
    episodeid: "Kebenaran Membingungkan",
    episodeen: "Chaotic Truth",
    exp: 7400000,
  ),
  ToramMQ(
    chapter: 8,
    chapterid: "Jalan ke Eldenbaum",
    chapteren: "Road to Eldenbaum",
    episode: 59,
    episodeid: "Tambang Hunian Para Monster",
    episodeen: "The Mine Where Monsters Lurk",
    exp: 8400000,
  ),
  ToramMQ(
    chapter: 8,
    chapterid: "Jalan ke Eldenbaum",
    chapteren: "Road to Eldenbaum",
    episode: 60,
    episodeid: "Bayangan Misterius",
    episodeen: "The Mysterious Shadow",
    exp: 8500000,
  ),
  ToramMQ(
    chapter: 8,
    chapterid: "Jalan ke Eldenbaum",
    chapteren: "Road to Eldenbaum",
    episode: 61,
    episodeid: "Negeri Baru Diel",
    episodeen: "The New Diel Country",
    exp: 8600000,
  ),
  ToramMQ(
    chapter: 8,
    chapterid: "Jalan ke Eldenbaum",
    chapteren: "Road to Eldenbaum",
    episode: 62,
    episodeid: "Persembunyian Relik Para Dewa",
    episodeen: "The Ruins of the Gods",
    exp: 8800000,
  ),
  ToramMQ(
    chapter: 8,
    chapterid: "Jalan ke Eldenbaum",
    chapteren: "Road to Eldenbaum",
    episode: 63,
    episodeid: "Dewa Keadilan Generasi Lalu",
    episodeen: "The Former God of Justice",
    exp: 9100000,
  ),
  ToramMQ(
    chapter: 8,
    chapterid: "Jalan ke Eldenbaum",
    chapteren: "Road to Eldenbaum",
    episode: 64,
    episodeid: "Takhta yang Tersisa di Kuil Dewa",
    episodeen: "The Remaining Thrones in the Shrine",
    exp: 9700000,
  ),
  ToramMQ(
    chapter: 8,
    chapterid: "Jalan ke Eldenbaum",
    chapteren: "Road to Eldenbaum",
    episode: 65,
    episodeid: "Keberadaan Para Dewa",
    episodeen: "God's Whereabouts",
    exp: 10400000,
  ),
  ToramMQ(
    chapter: 8,
    chapterid: "Jalan ke Eldenbaum",
    chapteren: "Road to Eldenbaum",
    episode: 66,
    episodeid: "Penantian di Kuil Dewi Spesies",
    episodeen: "The Wait at Specia's Shrine",
    exp: 11100000,
  ),
  ToramMQ(
    chapter: 8,
    chapterid: "Jalan ke Eldenbaum",
    chapteren: "Road to Eldenbaum",
    episode: 67,
    episodeid: "Pengawasan Es & Salju",
    episodeen: "The Warden of Ice & Snow",
    exp: 11800000,
  ),
  ToramMQ(
    chapter: 8,
    chapterid: "Jalan ke Eldenbaum",
    chapteren: "Road to Eldenbaum",
    episode: 68,
    episodeid: "Di Ujung Pegunungan",
    episodeen: "At Mountain's End",
    exp: 12500000,
  ),
  ToramMQ(
    chapter: 9,
    chapterid: "Perebutan Kembali Eldenbaum",
    chapteren: "Recapturing Eldenbaum",
    episode: 69,
    episodeid: "Jalan Maut Eldenbaum",
    episodeen: "Deadly Road to Eldenbaum",
    exp: 15800000,
  ),
  ToramMQ(
    chapter: 9,
    chapterid: "Perebutan Kembali Eldenbaum",
    chapteren: "Recapturing Eldenbaum",
    episode: 70,
    episodeid: "Perangkap Tak Terduga",
    episodeen: "Unforeseen Traps",
    exp: 17100000,
  ),
  ToramMQ(
    chapter: 9,
    chapterid: "Perebutan Kembali Eldenbaum",
    chapteren: "Recapturing Eldenbaum",
    episode: 71,
    episodeid: "Jejak Kemajuan Teknologi",
    episodeen: "Traces of Technological Progress",
    exp: 18200000,
  ),
  ToramMQ(
    chapter: 9,
    chapterid: "Perebutan Kembali Eldenbaum",
    chapteren: "Recapturing Eldenbaum",
    episode: 72,
    episodeid: "Kenalan Tak Terduga",
    episodeen: "An Uexpcted Acquaintance,",
    exp: 19200000,
  ),
  ToramMQ(
    chapter: 9,
    chapterid: "Perebutan Kembali Eldenbaum",
    chapteren: "Recapturing Eldenbaum",
    episode: 73,
    episodeid: "Operasi Markas Pos Depan",
    episodeen: "Front Line Base Operation",
    exp: 20300000,
  ),
  ToramMQ(
    chapter: 9,
    chapterid: "Perebutan Kembali Eldenbaum",
    chapteren: "Recapturing Eldenbaum",
    episode: 74,
    episodeid: "Taktik Merebut Pelabuhan di Atas Pohon",
    episodeen: "Strategy to Redeem the Treetop Harbor",
    exp: 21500000,
  ),
  ToramMQ(
    chapter: 9,
    chapterid: "Perebutan Kembali Eldenbaum",
    chapteren: "Recapturing Eldenbaum",
    episode: 75,
    episodeid: "Alat Pemindah Pusaka",
    episodeen: "The Teleporter Left Behind",
    exp: 22700000,
  ),
  ToramMQ(
    chapter: 9,
    chapterid: "Perebutan Kembali Eldenbaum",
    chapteren: "Recapturing Eldenbaum",
    episode: 76,
    episodeid: "Pria Pencari Maut",
    episodeen: "The Man Who Seeks Death",
    exp: 23900000,
  ),
  ToramMQ(
    chapter: 9,
    chapterid: "Perebutan Kembali Eldenbaum",
    chapteren: "Recapturing Eldenbaum",
    episode: 77,
    episodeid: "Perebutan Kembali Eldenbaum",
    episodeen: "The Battle to Recapture Eldenbaum",
    exp: 25000000,
  ),
  ToramMQ(
    chapter: 9,
    chapterid: "Perebutan Kembali Eldenbaum",
    chapteren: "Recapturing Eldenbaum",
    episode: 78,
    episodeid: "?",
    episodeen: "A New Beginning",
    exp: 13000000,
  ),
  ToramMQ(
    chapter: 10,
    chapterid: "Kapal Dewa yang Hilang",
    chapteren: "The Lost God's Ship",
    episode: 79,
    episodeid: "Menuju Tempat yang Ditakdirkan",
    episodeen: "Off to the Fateful Land",
    exp: 26000000,
  ),
  ToramMQ(
    chapter: 10,
    chapterid: "Kapal Dewa yang Hilang",
    chapteren: "The Lost God's Ship",
    episode: 80,
    episodeid: "Penghuni Bawah Tebing",
    episodeen: "The Inhabitants Under the Cliff",
    exp: 27400000,
  ),
  ToramMQ(
    chapter: 10,
    chapterid: "Kapal Dewa yang Hilang",
    chapteren: "The Lost God's Ship",
    episode: 81,
    episodeid: "Kembalinya Mimpi Buruk",
    episodeen: "The Nightmare Returns",
    exp: 28800000,
  ),
  ToramMQ(
    chapter: 10,
    chapterid: "Kapal Dewa yang Hilang",
    chapteren: "The Lost God's Ship",
    episode: 82,
    episodeid: "Keberadaan Para Biarawan yang Hilang",
    episodeen: "The Whereabouts of the Missing Monks",
    exp: 30200000,
  ),
  ToramMQ(
    chapter: 10,
    chapterid: "Kapal Dewa yang Hilang",
    chapteren: "The Lost God's Ship",
    episode: 83,
    episodeid: "Sang Dewi Keadilan dan Penghuni Ilegal",
    episodeen: "The Goddess of Justice and the Squatters",
    exp: 31600000,
  ),
  ToramMQ(
    chapter: 10,
    chapterid: "Kapal Dewa yang Hilang",
    chapteren: "The Lost God's Ship",
    episode: 84,
    episodeid: "Navigasi Bahtera",
    episodeen: "Navigator of the Ark",
    exp: 33100000,
  ),
  ToramMQ(
    chapter: 10,
    chapterid: "Kapal Dewa yang Hilang",
    chapteren: "The Lost God's Ship",
    episode: 85,
    episodeid: "Penyihir di Dalam Rimba",
    episodeen: "The Witch in the Woods",
    exp: 34600000,
  ),
  ToramMQ(
    chapter: 10,
    chapterid: "Kapal Dewa yang Hilang",
    chapteren: "The Lost God's Ship",
    episode: 86,
    episodeid: "Duel di Nov Diela",
    episodeen: "The Duel in Nov Diela",
    exp: 36200000,
  ),
  //   chap 11
  ToramMQ(
    chapter: 11,
    chapterid: "Off to Toram",
    chapteren: "Off to Toram",
    episode: 87,
    episodeid: "Penerbangan Bahtera",
    episodeen: "Flying the Ark",
    exp: 37800000,
  ),
  ToramMQ(
    chapter: 11,
    chapterid: "Off to Toram",
    chapteren: "Off to Toram",
    episode: 88,
    episodeid: "Daratan yang Tak Dikenal",
    episodeen: "Land of the Unknown",
    exp: 49000000,
  ),
  ToramMQ(
    chapter: 11,
    chapterid: "Off to Toram",
    chapteren: "Off to Toram",
    episode: 89,
    episodeid: "Hutan Berjalan",
    episodeen: "The Strolling Fores",
    exp: 51000000,
  ),
  ToramMQ(
    chapter: 11,
    chapterid: "Off to Toram",
    chapteren: "Off to Toram",
    episode: 90,
    episodeid: "Manusia Hutan Eumano",
    episodeen: "Eumanos the Forest Dwellers",
    exp: 53400000,
  ),
  ToramMQ(
    chapter: 11,
    chapterid: "Off to Toram",
    chapteren: "Off to Toram",
    episode: 91,
    episodeid: "Kaum Bertunas",
    episodeen: "A Sproutling is Born",
    exp: 55700000,
  ),
  ToramMQ(
    chapter: 11,
    chapterid: "Off to Toram",
    chapteren: "Off to Toram",
    episode: 92,
    episodeid: "Sang Pembawa Berkah",
    episodeen: "The Blessing-Bearer",
    exp: 58100000,
  ),
  ToramMQ(
    chapter: 11,
    chapterid: "Off to Toram",
    chapteren: "Off to Toram",
    episode: 93,
    episodeid: "Pertarungan Sengit di Markas Coenubia",
    episodeen: "Intense Battle in Coenubia's Stronghold",
    exp: 60500000,
  ),
  ToramMQ(
    chapter: 11,
    chapterid: "Off to Toram",
    chapteren: "Off to Toram",
    episode: 94,
    episodeid: "Bayangan Gunung Berasap",
    episodeen: "The Shadow of a Smoky Mountain",
    exp: 63000000,
  ),
];
